version: '3.8'
#
#services:
#  app:
#    image: db-application:3.0
#    ports:
#      - "9090:9090"
#    depends_on:
#      - redis
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#
#volumes:
#  redis_data:
services:
  app:
    build: .
    ports:
      - "8085:8085"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"